
 <!DOCTYPE html>
 <html>
 <head>
     <title>This Email generated by LMS</title>
 </head>
 <body>
     <h3>User Name : {{ $user['name'] }}</h3>
     <h3>Email : {{ $user['email'] }}</h3>
     <h3>Password : {{ $user['password'] }}</h3>
 </body>
 </html>
