
 <!DOCTYPE html>
 <html>
 <head>
     <title>This Email Generated by LMS System </title>
 </head>
 <body>
     <h3>Course  Name : {{ $user['course'] }}</h3>
     <h3>Batch Name : {{ $user['batch'] }}</h3>
 </body>
 </html>
